version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: chat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chatapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

  backend:
    build: ./backend
    container_name: chat-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/chatapp?authSource=admin
      JWT_SECRET: mySecretKey123456789012345678901234567890
      CLOUDINARY_CLOUD_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://frontend:3000
    depends_on:
      - mongodb
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - chat-network

volumes:
  mongodb_data:

networks:
  chat-network:
    driver: bridge
